In [1]:
import torch
import numpy as np


In [11]:
a=torch.rand(4,4)

print(a.shape)
print(a)
print(torch.__version__)

torch.Size([4, 4])
tensor([[0.3795, 0.8652, 0.3925, 0.7169],
        [0.6028, 0.9451, 0.3542, 0.5191],
        [0.1746, 0.6632, 0.9258, 0.7647],
        [0.3665, 0.7254, 0.5587, 0.0506]])
1.8.0.dev20210121+cu110


In [12]:
print(torch.square(a))

tensor([[0.1441, 0.7486, 0.1541, 0.5139],
        [0.3634, 0.8932, 0.1255, 0.2695],
        [0.0305, 0.4399, 0.8570, 0.5848],
        [0.1343, 0.5262, 0.3122, 0.0026]])


In [15]:


print(torch.cat([a,b],dim=0))

tensor([[0.3795, 0.8652, 0.3925, 0.7169],
        [0.6028, 0.9451, 0.3542, 0.5191],
        [0.1746, 0.6632, 0.9258, 0.7647],
        [0.3665, 0.7254, 0.5587, 0.0506],
        [0.1441, 0.7486, 0.1541, 0.5139],
        [0.3634, 0.8932, 0.1255, 0.2695],
        [0.0305, 0.4399, 0.8570, 0.5848],
        [0.1343, 0.5262, 0.3122, 0.0026]])


In [15]:
a=torch.tensor([[0,0,0,4,4,0,0,0,0,0,0],
           [0,0,3,0,0,0,3,0,0,0,0],
           [0,0,0,1,2,0,5,0,0,0,0],
           [0,5,0,1,0,0,0,0,0,0,0],
           [0,1,0,3,0,0,0,2,0,1,0],
           [0,1,0,0,4,0,0,0,0,1,0],
           [0,0,2,0,0,0,0,4,0,0,0],
           [1,0,0,2,1,0,0,3,4,0,1],
           [0,2,0,5,4,0,0,0,5,0,0],
           [3,3,0,2,1,0,3,0,2,0,1]])

In [18]:
b=torch.tensor([2,1,3,4,4,5,3,2,1,4,3])

TypeError: det() takes 1 positional argument but 2 were given